name: Update CIOs and mutual companies

on:
  schedule:
    - cron: "5 4 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Data update

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Update CSV with latest data
        run: |
          uv run scripts/update-cio-company-numbers.py
          uv run scripts/update-mutual-companies.py
        env:
          COMPANY_HOUSE_API_KEY: ${{ secrets.COMPANY_HOUSE_API_KEY }}
          FTC_DB_URL: ${{ secrets.FTC_DB_URL }}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update by GitHub Action" -a)
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
